---
- hosts: 192.168.3.40
  become: true
  become_user: root
  tasks:
    - name: Update apt 
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages
      apt: upgrade=dist force_apt_get=yes
